[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
julia = "1.11"                 # ★ Juliaのバージョンを指定 (1.11.2 を使っているので "1.11" としました)
Conda = "1"                    # Conda.jl はメジャーバージョン1台で安定
DataFrames = "1.7"             # ★ DataFrames v1.7.0 がインストールされたので、1.7以降を指定
Distributions = "0.25"         # ★ Distributions.jl の一般的な互換バージョン
HiGHS = "1.12.2"               # 既存の指定を維持 (もしJulia 1.11で問題があれば最新版を検討)
IntervalArithmetic = "0.22.19" # 既存の指定を維持 (もしJulia 1.11で問題があれば最新版を検討)
Ipopt = "1.6.7"                # 既存の指定を維持 (もしJulia 1.11で問題があれば最新版を検討)
JuMP = "1"                     # JuMP.jl はメジャーバージョン1台で安定
LaTeXStrings = "1"             # LaTeXStrings.jl はメジャーバージョン1台で安定
Plots = "1"                    # Plots.jl はメジャーバージョン1台で安定
PyPlot = "2"                   # PyPlot.jl はメジャーバージョン2台で安定
StatsPlots = "0.15"            # StatsPlots.jl の一般的な互換バージョン
StringEncodings = "0.3"        # StringEncodings.jl の一般的な互換バージョン